// e_commerce/app/src/views/About.vue
<template>
  <div class="about mt-5">
    <h1>About page</h1>
    <p>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
      Cumque ratione beatae qui ipsam quibusdam quidem deleniti delectus saepe, 
      esse distinctio, fuga amet adipisci eveniet incidunt magni quia perferendis consectetur placeat!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
      Cumque ratione beatae qui ipsam quibusdam quidem deleniti delectus saepe, 
      esse distinctio, fuga amet adipisci eveniet incidunt magni quia perferendis consectetur placeat!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
      Cumque ratione beatae qui ipsam quibusdam quidem deleniti delectus saepe, 
      esse distinctio, fuga amet adipisci eveniet incidunt magni quia perferendis consectetur placeat!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
      Cumque ratione beatae qui ipsam quibusdam quidem deleniti delectus saepe, 
      esse distinctio, fuga amet adipisci eveniet incidunt magni quia perferendis consectetur placeat!
    </p>
    <p>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
      Cumque ratione beatae qui ipsam quibusdam quidem deleniti delectus saepe, 
      esse distinctio, fuga amet adipisci eveniet incidunt magni quia perferendis consectetur placeat!
    </p>
  </div>
</template>

// e_commerce_react/app/src/views/About.js
import React from 'react'

export default function About(){
    return(
        <div>
            <h1>About</h1>
            <p>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
            </p>
        </div>
    )
}
