// e_commerce_react/app/src/views/Home.js
import React from 'react'

export default function Home(){
    return(
        <div>
            <h1>Home</h1>
            <p>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, molestiae.
            </p>
        </div>
    )
}

// e_commerce/app/src/views/Home.vue
<template>
  <div class="mt-5">
    <h1>Home</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
      Ut rem, nam architecto voluptates aut numquam ex doloremque! 
      Ipsa hic dolorum aliquid repellat error, 
      quibusdam odio ea architecto, id, temporibus aut!
    </p>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
      Ut rem, nam architecto voluptates aut numquam ex doloremque! 
      Ipsa hic dolorum aliquid repellat error, 
      quibusdam odio ea architecto, id, temporibus aut!
    </p>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
      Ut rem, nam architecto voluptates aut numquam ex doloremque! 
      Ipsa hic dolorum aliquid repellat error, 
      quibusdam odio ea architecto, id, temporibus aut!
    </p>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
      Ut rem, nam architecto voluptates aut numquam ex doloremque! 
      Ipsa hic dolorum aliquid repellat error, 
      quibusdam odio ea architecto, id, temporibus aut!
    </p>
  </div>
</template>

<script>


export default {
  name: 'Home'
}
</script>
